[CS-107] Visualização Gráfica das Lixeiras em um Mapa
SteffanoP/cata-sucata pull request #14
Opened 2023-08-20 20:39 UTC by vicentegalencar

2023-08-21 03:04 UTC, SteffanoP commented
Olá @vicentegalencar!

Vamos avaliar sua Pull Request em breve, enquanto isso você poderia corrigir os conflitos de Merge?

@Koda-ms você teria tempo para fazer a revisão da PR? Estou com o tempo apertado nessa semana, e acredito que você pode dar um feedback melhor do que eu.

2023-08-21 22:39 UTC, Koda-ms requested changes
Oi, @vicentegalencar , boa noite! Estava fazendo a revisão aqui da PR e a primeira coisa que gostaria de pedir é a mudança do diretório de onde estão suas implementações. Gostaria que você colocasse seu projeto na pasta `fronteend` prestando a atenção nas devidas subpastas existentes. Essa alteração é apenas para mantermos o projeto real em um único local.

2023-08-21 22:47 UTC, Koda-ms commented
> Oi, @vicentegalencar , boa noite! Estava fazendo a revisão aqui da PR e a primeira coisa que gostaria de pedir é a mudança do diretório de onde estão suas implementações. Gostaria que você colocasse seu projeto na pasta `fronteend` prestando a atenção nas devidas subpastas existentes. Essa alteração é apenas para mantermos o projeto real em um único local.

Perdão, Vicente. Percebi que a _branch_ não tinha atualizado aqui para mim. Está tudo certo em relação aos diretórios. ;)

2023-08-22 03:13 UTC, Koda-ms approved these changes
Congrats! 🥳🎊🎉

2023-08-22 03:17 UTC, merged