Exemplo login azure
SteffanoP/cata-sucata pull request #2
Opened 2023-08-06 22:35 UTC by ronaldo26rodrigues

Este PR adiciona um código de exemplo de como implementar o login utilizando as credenciais da Microsoft em um app React, que será utilizado no frontend do projeto CataSucata

Este código foi desenvolvido seguindo o tutorial disponível na [documentação da Microsoft](https://learn.microsoft.com/en-us/azure/active-directory/develop/single-page-app-tutorial-01-register-app)

2023-08-06 23:27 UTC, SteffanoP requested changes
Opa @ronaldo26rodrigues ! Muito boa a implementação para o time. Ainda assim, acredito que possamos melhorar em alguns pontos:

- Remover os arquivos gerados automaticamente pelo node (ex.: `package-lock.json`);
- Renomear a pasta `frontent` para `frontend`.

2023-08-07 01:40 UTC, ronaldo26rodrigues commented
Opa @SteffanoP, os arquivos `package.json` e `package-lock.json` são criados pelo NPM para especificar as dependências e pacotes instalados no projeto, e devem sempre ser commitados (lembra do requirements.txt do python?)

2023-08-07 01:40 UTC, ronaldo26rodrigues commented
E vou mudar esse nome da pasta, foi mal pelo miss click kkk :P

2023-08-07 01:53 UTC, SteffanoP commented
> Opa @SteffanoP, os arquivos `package.json` e `package-lock.json` são criados pelo NPM para especificar as dependências e pacotes instalados no projeto, e devem sempre ser commitados (lembra do requirements.txt do python?)

Tranquilo @ronaldo26rodrigues , eu tinha minhas dúvidas sobre o `package-lock.json`. Mas acabei de ver [aqui](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json), que é uma recomendação do NPM. ~Apesar d'eu discordar fortemente disso~.

2023-08-08 01:11 UTC, SteffanoP approved these changes
LGTM!

2023-08-08 01:13 UTC, merged