CS-128-Sistema-Notificacoes-Usuario básico funcionando para juntar na main
SteffanoP/cata-sucata pull request #20
Opened 2023-08-28 22:22 UTC by Joaovcarvalho23

Sistema de notificações básico para o usuário. Ele por enquanto retorna quando uma lixeira está cheia e retorna quando há um dispositivo com defeito, retornando "unknow". Assim que o usuário visualizar a notificação e clicar em qualquer outra região da tela, a mensagem é dada como lida e o ícone de notificações pendentes some.
O que precisamos é de uma Id para as lixeiras, para passar de forma mais específica quais lixeiras estão cheias no momento e identificar o dispositivo de qual lixeira está defeituoso.

Foi criado um PopOver que exibe as notificações como PopUp's. A verificação é feita na página do Dashboard e a função é chamada no componente da Navbar.

2023-08-28 22:38 UTC, SteffanoP commented
@Joaovcarvalho23 resolve o conflito por favor.

2023-08-29 00:52 UTC, Koda-ms requested changes
Uma outra coisa que percebi aqui é quando mudamos de tela. Quando a notificação chega (status `Cheia`), e clicamos no ícone de sino, a bolinha vermelha com a numeração some. Porém, quando mudo de tela, por exemplo, para a tela de Mapa e retorno para a tela de Dashboard, **a bolinha vermelha com a numeração reaparece.** 

Isso não deveria acontecer, pois aquela notificação já foi lida, saca? Então, peço que você verifique isso também, por favor. 👌

2023-08-29 00:52 UTC, Koda-ms commented on fronteend/src/pages/Dashboard/index.jsx
> +        if (response.data.status_trash.full > 0) {
Oi, @Joaovcarvalho23 ! Estava revisando sua PR aqui e percebi umas inconsistências com relação a exibição de notificação quando o status da lixeira muda.

![Captura de tela 2023-08-28 213726](https://github.com/SteffanoP/cata-sucata/assets/66442236/241a2350-9f15-4434-946a-d04fbd2fc975)

Repare que nessa imagem acima, a notificação aparece e realmente diz que temos 2 lixeiras com o status de `Cheias`. Massa!

Porém, nessa imagem abaixo, quando o status de uma lixeira muda para `Média`, **a notificação não está parecendo.**

![Captura de tela 2023-08-28 214223](https://github.com/SteffanoP/cata-sucata/assets/66442236/65e476c1-2a28-4993-a143-eb4f36f0ffb6)

Acredito que o ponto seja justamente essa parte do código que destaco aí. É possível verificar que o seu `if `corresponde apenas para quando a lixeira está `Cheia`. Sugiro que você analise isso para os outros status também. ;)

2023-08-29 00:56 UTC, Koda-ms commented on fronteend/src/pages/Dashboard/index.jsx
> +        if (response.data.status_trash.full > 0) {
Esqueci de outro detalhe: a notificação também não aparece quando o status da lixeira é `Vazio`.

2023-08-29 01:01 UTC, Joaovcarvalho23 commented on fronteend/src/pages/Dashboard/index.jsx
> +        if (response.data.status_trash.full > 0) {
Entendi July, vou seguir com a implementação disso então! ;-)

Agora uma pergunta, quando tu muda o status da lixeira (nesse caso com 1 cheia e 1 média) acho que deve dar refresh na página... Tenta aí quando puder pfv.

Ah, e como tu fica mudando os status da lixeira? Pra eu poder ir testando aqui também

2023-08-29 01:16 UTC, Koda-ms commented on fronteend/src/pages/Dashboard/index.jsx
> +        if (response.data.status_trash.full > 0) {
Entendi, @Joaovcarvalho23 . Mas, veja, ainda assim não é o adequado atualizar a página para poder receber a notificação, pois ela deve ser "instantânea". Ou seja, a sua função de notificação deve ficar fazendo requests à API em um certo intervalo de tempo, vamos supor 30s. Já que as notificações mudam de acordo com o status (nesse ponto que estamos tratando), ela deve aparecer assim que o status mudar e não precisar atualizar a tela para tal.

Para poder testar as notificações junto às mudanças de status, você tem que pedir ajudar à @SteffanoP , pois é ele quem muda lá no sensor.

2023-08-29 12:17 UTC, Joaovcarvalho23 commented on fronteend/src/pages/Dashboard/index.jsx
> +        if (response.data.status_trash.full > 0) {
Tudo bem @Koda-ms ! No problem!
Acredito que passando essa 'const interval' dentro de um userEffect(() =>{}) talvez já funcione!
Quando eu tiver tempo hoje a tarde, eu tento isso e se funcionar eu subo o commit para revisão :)

2023-08-30 01:58 UTC, GansoHub commented
As notificações estão atualizando em tempo real e podem ser visualizadas, retirando a sinalização da bolinha vermelha acima do sino, mas quando trocamos de página as notificações voltam a ser postas como não visualizadas e a sinalização volta.

2023-08-30 02:07 UTC, GansoHub commented
![Visualização](https://github.com/SteffanoP/cata-sucata/assets/77673388/66f4a211-7830-475f-a2bb-3d43686130fe)
As notificações estão sendo lidas e são atualizadas em tempo real, inclusive com a quantidade de lixeiras a serem realizadas coleta.
![2lixeiras](https://github.com/SteffanoP/cata-sucata/assets/77673388/93d1b36b-398f-4fb1-a0a0-bfc1fe08ea4b)
Mas as notificações são marcadas como não visualizadas caso a tela seja recarregada.

2023-08-30 03:00 UTC, Koda-ms commented
Opa, @Joaovcarvalho23 ! Pelo visto, @GansoHub quando fez a nova percebeu que as notificação continuam reaparecendo quando a página é atualizada. Você poderia verificar isso novamente, por favor?

2023-08-30 12:56 UTC, GansoHub commented
Vi agora, e testei entrar e sair da página, não apenas as notificações estão mais completas, como também de fato não voltam a ser tidas como não lidas ao sair da página, creio que está pronto para ser colocado como solucionado.
![Captura de tela 2023-08-30 095615](https://github.com/SteffanoP/cata-sucata/assets/77673388/c43b6b7c-39d2-4316-8acd-a6bd59ec8a19)

2023-08-30 13:00 UTC, Koda-ms approved these changes
Bom dia, @Joaovcarvalho23 ! Acabei de revisar sua PR e os pontos que abordamos aqui foram solucionados. Muito obrigada! 

**Tenho apenas um detalhe**: realmente quando trocamos de página e retornamos para o `Dashboard`, a bolinha vermelha não aparece mais, porém **quando atualizamos a página de `Dashboard` ela reaparece.** 
Eu não colocarei isso como um impedimento para aprovar sua PR, entretanto deixarei elencado na parte de _Issues_ para que possa ser solucionado posteriormente, haja vista que temos outras atividades mais importantes no momento. 

No mais, é isso! Parabéns pela PR e vamos seguindo! 🚀\o/

2023-08-30 13:08 UTC, merged