API Pública de coleta de dados
SteffanoP/cata-sucata pull request #23
Opened 2023-09-04 02:19 UTC by ronaldo26rodrigues

Esta PR implementa as funçõess públicas para consulta dos dados do sistema
##
Aqui o retorno dos dados depende da configuração `is_public`, definida pelo gerente de coleta
## Funções
`list-areacoleta-public`: retorna todas as áreas de coleta
`list-sensor-public`: retorna todos os sensores
`list-sensordata-public`: retorna todo o histórico dos sensores
`list-sensordata-public-days`: retorna o histórico dos sensores entre duas datas. E.g. {"start":"2023-08-30T19:21:27.0000000Z", "end":"2023-08-31T19:21:27.0000000Z"}. Caso `"end"` não seja informado, será considerada a data atual

2023-09-05 00:39 UTC, Ant4r3z approved these changes

2023-09-05 01:49 UTC, SteffanoP requested changes, later dismissed
Opa @ronaldo26rodrigues, já fiz alguns testes aqui e verifiquei que a `list-areacoleta-public` não está restrigindo quando faz o set para o privado.

Você poderia verificar isso?

2023-09-05 02:49 UTC, ronaldo26rodrigues commented
Opa @SteffanoP, corrigi aqui, faltava um parâmetro no `body`. 
O body dessa rota tem os seguindos dados:
```json
{
    "id": "gerente_de_coleta",
    "prop": "gerente",
    "is_public": false
}
```

2023-09-06 01:04 UTC, Ant4r3z approved these changes

2023-09-06 01:34 UTC, merged