tela de documentação
SteffanoP/cata-sucata pull request #26
Opened 2023-09-05 20:39 UTC by vicentegalencar

Tela de documentação

2023-09-05 21:38 UTC, Koda-ms requested changes
Oi, @vicentegalencar ! Tudo bem? 
Estava verificando sua PR aqui e quero lhe agradecer, primeiramente, pela implementação. 🎉 Porém, eu percebi que a tela de documentação ficou muito grande. 😬 Não tenho certeza se isso é diferente de monitor para monitor, mas você poderia diminuir um pouco a visualização de toda a caixa? 

Além disso, talvez fosse mais interessante colocar um ícone de seta para representar o botão de retorno à tela anterior (como na ilustração da imagem abaixo), ao invés do botão azul existente. Mas, isso é apenas uma sugestão. 😉

![Captura de tela 2023-09-05 183248](https://github.com/SteffanoP/cata-sucata/assets/66442236/3395ebbb-4a83-476e-b5fd-3b4eac74dffa)

2023-09-05 21:43 UTC, Joaovcarvalho23 approved these changes
Ficou muito bom Vicente!! Parabéns!!!

2023-09-06 03:24 UTC, ronaldo26rodrigues commented
Oi @vicentegalencar! Só falta uma rota aí nessa tela:

`/list-sensordata-public-areacoleta`

2023-09-06 03:37 UTC, Koda-ms approved these changes
Massa, @vicentegalencar ! Muito obrigada pela sua PR e já pode dar `merge`! 🎉🎉

2023-09-06 03:37 UTC, merged